import { Task } from './types';

export const initialTasks: Task[] = [
  // Produksi
  {
    id: 'prod-1',
    title: 'Formula print/work sheets bug',
    description: 'Formula print/work sheets bug untuk tampilan tidak terupdate',
    category: 'Produksi',
    status: 'Done',
    priority: 'High',
    ownerId: 'system', createdAt: Date.now() - 1000000,
    comments: [],
  },
  {
    id: 'prod-2',
    title: 'Search nama atau kode cat terupdate',
    description: 'Search nama atau kode cat mohon untuk langsung terupdate tidak harus klik per page',
    category: 'Produksi',
    status: 'New',
    priority: 'Medium',
    ownerId: 'system', createdAt: Date.now() - 900000,
    comments: [],
  },
  {
    id: 'prod-3',
    title: 'Tambahkan kolom pic di star qc',
    description: 'Tambakan kolom pic yang membuat cat tersebut di bagian dalam star qc',
    category: 'Produksi',
    status: 'New',
    priority: 'Medium',
    ownerId: 'system', createdAt: Date.now() - 800000,
    comments: [],
  },
  {
    id: 'prod-4',
    title: 'SPK in progress padahal belum assign formula',
    description: 'Beberapa spk statusnya in progress padahal belum assign formula',
    category: 'Produksi',
    status: 'New',
    priority: 'High',
    ownerId: 'system', createdAt: Date.now() - 700000,
    comments: [],
  },
  {
    id: 'prod-5',
    title: 'List produk untuk create restock spk',
    description: 'Tambahkan list produk untuk create restock spk',
    category: 'Produksi',
    status: 'New',
    priority: 'Medium',
    ownerId: 'system', createdAt: Date.now() - 600000,
    comments: [],
  },
  {
    id: 'prod-6',
    title: 'Kode produk pada form tidak sinkron',
    description: 'Kode produk pada form pengambilan bahan baku tidak sinkron dengan worksheet',
    category: 'Produksi',
    status: 'New',
    priority: 'High',
    ownerId: 'system', createdAt: Date.now() - 500000,
    comments: [],
  },
  {
    id: 'prod-7',
    title: 'Tambahkan warna pada form bahan baku',
    description: 'Tambahkan warna pada form pengambilan bahan baku',
    category: 'Produksi',
    status: 'New',
    priority: 'Low',
    ownerId: 'system', createdAt: Date.now() - 400000,
    comments: [],
  },
  {
    id: 'prod-8',
    title: 'Kemasan formula tidak muncul di worksheet',
    description: 'Kemasan yang dipilih pada formula tidak muncul di worksheet (no packagaing selected)',
    category: 'Produksi',
    status: 'New',
    priority: 'Medium',
    ownerId: 'system', createdAt: Date.now() - 300000,
    comments: [],
  },
  {
    id: 'prod-9',
    title: 'Penambahan kolom Print worksheet kompenan warna',
    description: 'Penambahan kolom pada Print worksheet untuk tempat komponen warna pasta, dan penyesuaian ukuran agar bisa cukup dalam 1 lembar kertas WS',
    category: 'Produksi',
    status: 'New',
    priority: 'Medium',
    ownerId: 'system', createdAt: Date.now() - 200000,
    comments: [],
  },

  // RMC
  {
    id: 'rmc-1',
    title: 'Formula pembuatan RMC tidak wajib',
    description: 'Formula untuk pembuatan RMC tidak wajib 100%',
    category: 'RMC',
    status: 'Done',
    priority: 'Medium',
    ownerId: 'system', createdAt: Date.now() - 190000,
    comments: [],
  },
  {
    id: 'rmc-2',
    title: 'TDS List',
    description: 'TDS List',
    category: 'RMC',
    status: 'In Progress',
    priority: 'Medium',
    ownerId: 'system', createdAt: Date.now() - 180000,
    comments: [],
  },

  // Finance
  {
    id: 'fin-1',
    title: 'PI PO customer sudah bayar',
    description: 'PI untuk PO customer yang sudah bayar',
    category: 'Finance',
    status: 'Done',
    priority: 'High',
    ownerId: 'system', createdAt: Date.now() - 170000,
    comments: [],
  },
  {
    id: 'fin-2',
    title: 'Record Payment tidak berfungsi',
    description: 'Record Payment tidak berfungsi',
    category: 'Finance',
    status: 'Done',
    priority: 'High',
    ownerId: 'system', createdAt: Date.now() - 160000,
    comments: [],
  },
  {
    id: 'fin-3',
    title: 'Print invoice perusahaan & pribadi',
    description: 'Print invoice untuk perusahaan Dan pribadi',
    category: 'Finance',
    status: 'In Progress',
    priority: 'Medium',
    ownerId: 'system', createdAt: Date.now() - 150000,
    comments: [],
  },
  {
    id: 'fin-4',
    title: 'Penyesuaian Pajak Invoice',
    description: 'Penyesuaian tampilan Pajak dan perhitungan untuk ke invoice',
    category: 'Finance',
    status: 'Done',
    priority: 'High',
    ownerId: 'system', createdAt: Date.now() - 140000,
    comments: [],
  },
  {
    id: 'fin-5',
    title: 'Pengajuan Anggaran',
    description: 'Pengajuan Anggaran (Kebuthan OPS perusahaan)',
    category: 'Finance',
    status: 'In Progress',
    priority: 'Medium',
    ownerId: 'system', createdAt: Date.now() - 130000,
    comments: [],
  },
  {
    id: 'fin-6',
    title: 'Pengajuan pembelian barang',
    description: 'Pengajuan penbelian barang (dari Procurement)',
    category: 'Finance',
    status: 'Done',
    priority: 'Medium',
    ownerId: 'system', createdAt: Date.now() - 120000,
    comments: [],
  },
  {
    id: 'fin-7',
    title: 'Kop invoice pribadi elvian helmi',
    description: 'Untuk invoice pribadi diganti kopnya jadi elvian helmi',
    category: 'Finance',
    status: 'New',
    priority: 'Low',
    ownerId: 'system', createdAt: Date.now() - 110000,
    comments: [],
  },
  {
    id: 'fin-8',
    title: 'Record payment lebih jelas',
    description: 'Record payment dibuat lebih jelas biar keliatan mana yang udah dibayar atau belum',
    category: 'Finance',
    status: 'New',
    priority: 'Medium',
    ownerId: 'system', createdAt: Date.now() - 100000,
    comments: [],
  },
  {
    id: 'fin-9',
    title: 'Invoice beberapa sj',
    description: 'Bikin invoice untuk beberapa sj apakah bisa??',
    category: 'Finance',
    status: 'New',
    priority: 'Low',
    ownerId: 'system', createdAt: Date.now() - 90000,
    comments: [],
  },
  {
    id: 'fin-10',
    title: 'Total PO erp include pajak',
    description: 'Total Po di erp belum include pajak',
    category: 'Finance',
    status: 'New',
    priority: 'High',
    ownerId: 'system', createdAt: Date.now() - 80000,
    comments: [],
  },
  {
    id: 'fin-11',
    title: 'Revisi harga tidak masuk Invoice',
    description: 'Revisi harga dll tidak masuk ke dalam PO yang sudah di jadikan invoice',
    category: 'Finance',
    status: 'New',
    priority: 'High',
    ownerId: 'system', createdAt: Date.now() - 70000,
    comments: [],
  },

  // Inventory
  {
    id: 'inv-1',
    title: 'Surat Jalan untuk project/packing',
    description: 'Surat Jalan untuk project/packing list',
    category: 'Inventory',
    status: 'Done',
    priority: 'Medium',
    ownerId: 'system', createdAt: Date.now() - 60000,
    comments: [],
  },

  // Project
  {
    id: 'prj-1',
    title: 'Informasi PO tidak muncul',
    description: 'Informasi PO tidak muncul di LIST PROJECT',
    category: 'Project',
    status: 'New',
    priority: 'Medium',
    ownerId: 'system', createdAt: Date.now() - 50000,
    comments: [],
  },

  // Procurement
  {
    id: 'proc-1',
    title: 'PO revisi tanpa merubah no PO',
    description: 'PO dapat di revisi tanpa merubah no PO yg awal',
    category: 'Procurement',
    status: 'New',
    priority: 'Medium',
    ownerId: 'system', createdAt: Date.now() - 40000,
    comments: [],
  },
  {
    id: 'proc-2',
    title: 'Searching supplier belum bisa',
    description: 'Searching supplier belum bisa',
    category: 'Procurement',
    status: 'New',
    priority: 'High',
    ownerId: 'system', createdAt: Date.now() - 39000,
    comments: [],
  },
  {
    id: 'proc-3',
    title: 'Pengajuan Raw Material ERP',
    description: 'Pengajuan Raw Material Belum bisa pakai ERP , coba mulai trial dr Inventory',
    category: 'Procurement',
    status: 'New',
    priority: 'Medium',
    ownerId: 'system', createdAt: Date.now() - 38000,
    comments: [],
  },
  {
    id: 'proc-4',
    title: 'Menggabungkan PO supplier sama',
    description: 'Menggabungkan PO ke supplier yg sama',
    category: 'Procurement',
    status: 'New',
    priority: 'Low',
    ownerId: 'system', createdAt: Date.now() - 37000,
    comments: [],
  },
  {
    id: 'proc-5',
    title: 'Merubah stts PO sudah dikirim',
    description: 'Purchasing belum bisa merubah stts PO sudah di kirim',
    category: 'Procurement',
    status: 'New',
    priority: 'High',
    ownerId: 'system', createdAt: Date.now() - 36000,
    comments: [],
  },
  {
    id: 'proc-6',
    title: 'Tambahkan kolom diskon rupiah',
    description: 'Tambahkan kolom diskon (dalam rupiah)',
    category: 'Procurement',
    status: 'New',
    priority: 'Low',
    ownerId: 'system', createdAt: Date.now() - 35000,
    comments: [],
  },

  // Marketing/Sales
  {
    id: 'mkt-1',
    title: 'Leads data customer',
    description: 'Leads data customer',
    category: 'Marketing/Sales',
    status: 'Waiting',
    priority: 'Medium',
    ownerId: 'system', createdAt: Date.now() - 30000,
    comments: [],
  },
  {
    id: 'mkt-2',
    title: 'List produk cat tersedia',
    description: 'List produk cat yang tersedia',
    category: 'Marketing/Sales',
    status: 'Waiting',
    priority: 'Low',
    ownerId: 'system', createdAt: Date.now() - 29000,
    comments: [],
  },
  {
    id: 'mkt-3',
    title: 'No PO pada list PO print',
    description: 'Nomor PO pada list PO customer dan print',
    category: 'Marketing/Sales',
    status: 'Waiting',
    priority: 'Medium',
    ownerId: 'system', createdAt: Date.now() - 28000,
    comments: [],
  },
  {
    id: 'mkt-4',
    title: 'Tambah no po customer dashboard',
    description: 'Tambah no po customer di dashboard, di PI dan SJ',
    category: 'Marketing/Sales',
    status: 'Waiting',
    priority: 'Medium',
    ownerId: 'system', createdAt: Date.now() - 27000,
    comments: [],
  },
  {
    id: 'mkt-5',
    title: 'Tambah item packing kayu',
    description: 'Tambah item packing kayu',
    category: 'Marketing/Sales',
    status: 'Waiting',
    priority: 'Low',
    ownerId: 'system', createdAt: Date.now() - 26000,
    comments: [],
  },
  {
    id: 'mkt-6',
    title: 'Laporan PO per bulan excel',
    description: 'Laporan PO per bulan bisa diexport jadi bentuk excel',
    category: 'Marketing/Sales',
    status: 'Waiting',
    priority: 'Medium',
    ownerId: 'system', createdAt: Date.now() - 25000,
    comments: [],
  },
];
